### ISSUE TITLE
Evaluation 30 October

### ISSUE THREAD

**Issue by camillethuyentruong** [Melcatus/genomic_cotton#10]
Hi Melania,

Your repo is well-organized and easy to read. I have only made minor English corrections to your README files. Well done!

If you have some preliminary results already, I suggest you make a "results" folder where you can present the results of your analyses that correspond to your code (figures, graphics). This could later be added as a link for supplementary materials in your future publication.

I suggest you make a "presentation" folder where you can put the files from your presentations is class (general_expo_project.pdf, currently in the meta folder; metodological_exposition.md). It would also be nice to make an additional folder with the issues that you presented in class.

**Comment by Melcatus** [comment]
Hi Camille, 
thanks for your comments and the corrections. At this time I could not get results, but I consider placing them in a different  directory to `/bin/`  `/data/` `/meta/`. 
I added a directory for the presentations I made in class `/presentations/` and another for the issues `/issues/`
