### ISSUE TITLE
How to prevent the end of disk space?

### ISSUE THREAD

**Issue by Melcatus** [Melcatus/genomic_cotton#11]
Hi everyone!
I have a issue because i run the software NGSEP and generates very large _log_ files, what are files  that records either events that occur in an operating system or other software runs, or messages between different users of a communication software.

I run the software NGSEP with the command: 

`java -jar -Xmx4000M NGSEPcore_3.3.2.jar MergeVCF ../data/variants_samples/TM-1_V2.1.fa.fai ../data/vcfs/A01_merge.vcf ../data/vcfs/A02_merge.vcf ../data/vcfs/A03_merge.vcf ../data/vcfs/C01_merge.vcf ../data/vcfs/C02_merge.vcf > ../data/vcfs/all_my_samples.vcf`

files _syslog_ were generated in the directory `/var/log/` of ~ 250GB, this causing that my computer colapse :( 

Searching in the forums ([forum1](https://www.cyberciti.biz/faq/remove-log-files-in-linux-unix-bsd/) or [forum2](http://www.linuxhispano.net/2014/04/21/vaciar-el-contenido-de-un-fichero-en-linux-sin-borrarlo/?fbclid=IwAR2MvEo16hX729ON_IFn0OeRoAe-h7NeUbbV6W7Ci2NpFFrSmasIbdxNisk)), some people say that the issue it resolves with remove the files and other people say that remove the file is dangerous to the system

My operating system is Ubuntu 18.04.3 LTS and my disk 1TB

So, wich the correct solution this problem?

Thanks for your attention

**Comment by FernandaDiaz12** [comment]
Hi Mel, I am not sure why  NGSEP is creating huge log files. However, that same program has a program with an interface. Where yo can run the command:

`MergeVCF`

To avoid whatever error is inducing the creation of big log files. 

 You can check the manual [here](http://ngsep.sourceforge.net/ManualNGSEP.htm#_Toc374444764).

**Comment by Melcatus** [comment]
Print the largest files or folders in the current dir

`du -k /var/log | sort -n | tail -5`

**Comment by FernandaDiaz12** [comment]
To "truncate" the syslog directory. 

`sudo truncate -s 0 /var/log/syslog`
