### ISSUE TITLE
What database use to cotton genome annotation?

### ISSUE THREAD

**Issue by Melcatus** [Melcatus/genomic_cotton#9]
Hi! I need help!
The genome annotation is a necesary step for predict the genes or proteins from of the differents sequences.

Exist many databases to do the annotation, they can of a specie diferent of ours or of a same specie that is generated from diferents projects. In the case of cotton exist a international project that gathers the more important data about _Gossypium hirsutum_, others domesticated species of cotton and their ancestors. This is project is [CottonGen](https://www.cottongen.org/)

In your page we can found differents assemblies the genomes sequenced with differents platforms, and with different software. 

https://www.cottongen.org/data/download/genome_tetraploid/AD1#CM

There are also files to make the annotation by:

[Transcript Alignments](https://github.com/Melcatus/genomic_cotton/blob/master/data/annotation/blat_AD1_transcript_ZJU_g.hirsutum_cottongen_reftransV1.p97.len97.gff3.gz)
 
[maker alignments](https://github.com/Melcatus/genomic_cotton/blob/master/data/annotation/marker_alignment_blat_AD1_ZJU_SNP.p90.len97.gaplt2.gapszlt2.gff3.gz)

[predicted gene alignments](https://github.com/Melcatus/genomic_cotton/blob/master/data/annotation/Predicted%20gene%20alignments_TM-1_V2.1.gene.gff.gz) 

These files were create from the ZJU genome assembly, this genome is my genome reference to mapping my samples. But, of the other assemblies there are others files: 

[Transcript Alignments](https://github.com/Melcatus/genomic_cotton/blob/master/data/annotation/other_transcript_blat_AD1_TxJGI_g.hirsutum_cottongen_refTransV1.p97.len97.gff3.gz)

[predicted gene alignments](https://github.com/Melcatus/genomic_cotton/blob/master/data/annotation/predicted_gene_alignment_Tx-JGI_G.hirsutum_v1.1.gene.gff3.gz)

And, in forums and personals tips, they mention that it is better to annotate with the largest possible number of databases but if we use the software [NGSEP](http://ngsep.sourceforge.net/ManualNGSEP.htm#_Toc374444765) for do variants annotation it's used the next command 

`java -jar NGSEPcore.jar Annotate <OPTIONS> <VARIANTS_FILE> <TRANSCRIPTOME_MAP> <REFERENCE_FILE> `

So, my question is: 
**Under what criteria do I choose the best files to write down my genomes?**

**Comment by Melcatus** [comment]
The genome annotation is a necesary step for predict the genes or proteins from of the differents sequences. 

Exist many data bases to do the annotation, they can of a specie diferent of ours or of a same specie that is generated from diferents projects. In the case of cotton exist a international project that gathers the more important data about _Gossypium hirsutum_, others domesticated species of cotton and their ancestors. This is project is [CottonGen](https://www.cottongen.org/).

In your page we can found differents assemblies the genomes sequenced with diferents plataforms, and with different software. Also,

**Comment by Martinez-Gregorio-Hector** [comment]
Hi Mel

If you mapping with **ZJU genome assembly** use the same to annotate. If you use another reference could have problems with the genomic coordinates.

best,

Héctor

**Comment by Melcatus** [comment]
Others functions 
https://github.com/vapniks/mergeutils

**Comment by Melcatus** [comment]
thanks !
